### PR TITLE
Add new locales to Gaia

### PR DESCRIPTION
**Pull request by TheoChevalier**
Creating the PR not to forget adding them.
Will comment here once https://bugzilla.mozilla.org/show_bug.cgi?id=1180023 and https://bugzilla.mozilla.org/show_bug.cgi?id=1181829 have landed and have been uplifted.

### CODE REVIEW

**Comment by flodolo** [comment]
Please make sure to add them only _after_ we have actual content in the repositories (we have several locales that are available in Gaia but don't have any content, I add them periodically).

**Comment by TheoChevalier** [comment]
You mean relevant content, not just initialized repos? Yeah, those locales are almost complete so we can just wait for the first import from Pootle

**Comment by flodolo** [comment]
Yes, relevant content for which makes sense to use Transvision's resources ;-)

**Comment by TheoChevalier** [comment]
Alright, Dwayne pushed content into the repos, I think this can be merged :)

**Pull request merged**
